package io.github.mzahidur.i18n.domain.model;

/**
 * Represents the origin of a resolved translation.
 *
 * <p>Used for auditability — every persisted {@link I18nMessage} records
 * which layer of the fallback chain produced it.</p>
 *
 * <p>Ordering reflects the fallback chain priority:</p>
 * <ol>
 *   <li>{@link #DB}         — fastest; already stored.</li>
 *   <li>{@link #PROPERTIES} — Spring {@code .properties} files.</li>
 *   <li>{@link #AI}         — generated on-demand; persisted for reuse.</li>
 * </ol>
 */
public enum TranslationSource {

    /**
     * Translation was retrieved from the {@code i18n_messages} database table.
     */
    DB,

    /**
     * Translation was resolved from a {@code .properties} resource bundle
     * via Spring's {@code ResourceBundleMessageSource}.
     */
    PROPERTIES,

    /**
     * Translation was generated by an AI provider (e.g. Spring AI / LangChain4j).
     * Entries with this source are persisted back to the DB to avoid repeat AI calls.
     */
    AI
}
